apiVersion: v1
kind: Service
metadata:
    name: "kalse-65a7"
    labels:
        app: "kalse-65a7"
spec:
    type: LoadBalancer
    ports:
    - port: 18610
      targetPort: 18610
      protocol: TCP
      name: http
    selector:
        app: "kalse-65a7"