on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n omkar123 -g omkar1239035-rg --location "East US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n omkar123 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n omkar123 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n omkar123 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: omkar123.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/hi" -f  "app.py" -t omkar123.azurecr.io/kalse:${{ github.sha }} --label dockerfile-path=app.py
        docker push omkar123.azurecr.io/kalse:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kalse_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kalse8150 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kalse8150`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kalse8150
        container-registry-url: omkar123.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kalsedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kalse8150
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          omkar123.azurecr.io/kalse:${{ github.sha }}
        imagepullsecrets: |
          kalsedockerauth   
